import React, { createContext, useState, useEffect } from 'react'

const translations = {
  en: {
    home: 'Home',
    hotels: 'Hotels',
    restaurants: 'Restaurants',
    events: 'Events',
    bookNow: 'Book Now',
    viewOnMap: 'View on Maps',
    totalDestinations: 'Total Destinations',
    totalBookings: 'Total Bookings',
    mostSearched: 'Most Searched',
    mostSaved: 'Most Saved',
    seasonalPopularity: 'Seasonal Popularity',
    confirmBooking: 'Confirm Booking',
    yourJourneyAwaits: 'Your Journey Awaits ✨',
    budget: 'Budget Planner',
    help: 'Help',
    rentals: 'Rentals',
    dishes: 'Famous Dishes',
    dressCode: 'Dress Code',
    transport: 'Transportation',
    pubs: 'Pubs',
    movies: 'Movies',
    malls: 'Malls',
    transportBooking: 'Transport Booking',
    states: 'States',
    hiddenPalaces: 'Hidden Palaces',
    foreignPalaces: 'Foreign Palaces',
    bestSeason: 'Best Season',
    compareHotels: 'Compare Hotels',
    preferences: 'Preferences',
  },
  hi: {
    home: 'होम',
    hotels: 'होटल',
    restaurants: 'रेस्टोरेंट',
    events: 'इवेंट्स',
    bookNow: 'अब बुक करें',
    viewOnMap: 'मानचित्र पर देखें',
    totalDestinations: 'कुल गंतव्य',
    totalBookings: 'कुल बुकिंग',
    mostSearched: 'सबसे अधिक खोजा गया',
    mostSaved: 'सबसे अधिक सहेजा गया',
    seasonalPopularity: 'मौसमी लोकप्रियता',
    confirmBooking: 'बुकिंग की पुष्टि करें',
    yourJourneyAwaits: 'आपकी यात्रा प्रतीक्षा कर रही है ✨',
    budget: 'बजट प्लैनर',
    help: 'मदद',
    rentals: 'किराये',
    dishes: 'प्रसिद्ध व्यंजन',
    dressCode: 'ड्रेस कोड',
    transport: 'परिवहन',
    pubs: 'पब',
    movies: 'फिल्में',
    malls: 'मॉल',
    transportBooking: 'परिवहन बुकिंग',
    states: 'राज्य',
    hiddenPalaces: 'छिपे महल',
    foreignPalaces: 'विदेशी महल',
    bestSeason: 'सबसे अच्छा समय',
    compareHotels: 'होटल तुलना',
    preferences: 'प्राथमिकताएँ',
  },
  fr: {
    home: 'Accueil',
    hotels: 'Hôtels',
    restaurants: 'Restaurants',
    events: 'Événements',
    bookNow: 'Réserver maintenant',
    viewOnMap: 'Voir sur la carte',
    totalDestinations: 'Destinations totales',
    totalBookings: 'Réservations totales',
    mostSearched: 'Le plus recherché',
    mostSaved: 'Le plus enregistré',
    seasonalPopularity: 'Popularité saisonnière',
    confirmBooking: 'Confirmer la réservation',
    yourJourneyAwaits: 'Votre voyage vous attend ✨',
    budget: 'Planificateur de budget',
    help: 'Aide',
    rentals: 'Locations',
    dishes: 'Plats célèbres',
    dressCode: 'Code vestimentaire',
    transport: 'Transport',
    pubs: 'Pubs',
    movies: 'Films',
    malls: 'Centres commerciaux',
    transportBooking: 'Réservation de transport',
    states: 'États',
    hiddenPalaces: 'Palais cachés',
    foreignPalaces: 'Palais étrangers',
    bestSeason: 'Meilleure saison',
    compareHotels: 'Comparer les hôtels',
    preferences: 'Préférences',
  },
  es: {
    home: 'Inicio',
    hotels: 'Hoteles',
    restaurants: 'Restaurantes',
    events: 'Eventos',
    bookNow: 'Reservar ahora',
    viewOnMap: 'Ver en el mapa',
    totalDestinations: 'Destinos totales',
    totalBookings: 'Reservas totales',
    mostSearched: 'Más buscado',
    mostSaved: 'Más guardado',
    seasonalPopularity: 'Popularidad estacional',
    confirmBooking: 'Confirmar reserva',
    yourJourneyAwaits: 'Tu viaje te espera ✨',
    budget: 'Planificador de presupuesto',
    help: 'Ayuda',
    rentals: 'Alquileres',
    dishes: 'Platos famosos',
    dressCode: 'Código de vestimenta',
    transport: 'Transporte',
    pubs: 'Pubs',
    movies: 'Películas',
    malls: 'Centros comerciales',
    transportBooking: 'Reserva de transporte',
    states: 'Estados',
    hiddenPalaces: 'Palacios ocultos',
    foreignPalaces: 'Palacios extranjeros',
    bestSeason: 'Mejor temporada',
    compareHotels: 'Comparar hoteles',
    preferences: 'Preferencias',
  },
}

export const LanguageContext = createContext({})

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en')
  useEffect(() => {
    localStorage.setItem('lang', lang)
  }, [lang])
  const t = (key) => translations[lang]?.[key] || translations.en[key] || key
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
